apiVersion: v1
kind: Service
metadata:
  name: certcheck
  namespace: certcheck
  labels:
    app: certcheck
spec:
  selector:
    app: certcheck
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80