name: Deploy to EKS

on:  
  push:
    branches: 
    - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to ECR
      run: $(aws ecr get-login --no-include-email)

    - name: Build and push certcheck docker image
      run: |
        docker build -t certchecker:latest .
        docker tag certchecker:latest 193404144226.dkr.ecr.eu-west-1.amazonaws.com/certchecker:latest
        docker push 193404144226.dkr.ecr.eu-west-1.amazonaws.com/certchecker:latest

    - name: Install kubectl
      run: |
        curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.13/2022-10-31/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
        echo 'export PATH=$PATH:$HOME/

    - name: Deploy to EKS
      run: |
        aws eks --region eu-west-1 update-kubeconfig --name k8s-cluster-5
        kubectl apply -f deployment.yaml
