name: Deploy to EKS

on:  
  push:
    branches: 
    - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Build and push certcheck docker image
      run: |
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 193404144226.dkr.ecr.eu-west-1.amazonaws.com
        docker build -t certchecker:latest certcheck/
        docker tag certchecker:latest 193404144226.dkr.ecr.eu-west-1.amazonaws.com/certchecker:latest
        docker push 193404144226.dkr.ecr.eu-west-1.amazonaws.com/certchecker:latest

    - name: Install kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl

    - name: Deploy to EKS
      run: |
        aws eks --region eu-west-1 update-kubeconfig --name k8s-cluster-5
        kubectl apply -f certcheck/deployment.yaml
